name: instant
description: A package that exports functions for converting, formatting, and nicening of dates/times in Dart.
version: 0.1.1+2
homepage: https://aditya-kishore.gitbook.io/instant/
repository: https://github.com/AKushWarrior/instant
author: Aditya Kishore <akushwarrior@gmail.com>
issue_tracker: https://github.com/AKushWarrior/instant/issues

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
